# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ParkingSearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='latitude',
            field=models.FloatField(default=30.52),
        ),
        migrations.AddField(
            model_name='parking',
            name='longitude',
            field=models.FloatField(default=30.3),
        ),
    ]
